DROP TABLE BANK CASCADE CONSTRAINTS;

 CREATE TABLE BANK (	
    BANK_ID VARCHAR2(20)CONSTRAINT PK_BANK PRIMARY KEY, 
	BANK_NAME VARCHAR2(40)
);

   COMMENT ON COLUMN BANK.BANK_ID IS '���� ���̵�';
   COMMENT ON COLUMN BANK.BANK_NAME IS '���� �̸�';
  
   
--SELECT * FROM BANK;
----------------------------------------------------------------------------------------------------------------


DROP TABLE MEMBER CASCADE CONSTRAINTS;

 CREATE TABLE MEMBER (	
    MEMBER_ID VARCHAR2(30) CONSTRAINT PK_MEMBER PRIMARY KEY, 
	MEMBER_PWD VARCHAR2(30) NOT NULL, 
    MEMBER_NAME VARCHAR2(50) NOT NULL, 
	EMAIL VARCHAR2(40), 
    PHONE VARCHAR2(30), 
	ADDRESS_NUM VARCHAR2(50),
	ADDRESS VARCHAR2(500), 
	ENROLL_DATE DATE, 
	BLACKLIST_FLAG VARCHAR2(1) CHECK(BLACKLIST_FLAG IN ('Y', 'N')),
    ADMIN_FLAG VARCHAR2(1) CHECK(ADMIN_FLAG IN ('Y', 'N')),
    PROFILE_IMG_ORINAME VARCHAR2(100),
    PROFILE_IMG_RENAME VARCHAR2(100),
    LAST_LOGIN_DATE DATE

);

   COMMENT ON COLUMN MEMBER.MEMBER_ID IS 'ȸ�����̵�';
   COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '��й�ȣ';
   COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '�̸�';;
   COMMENT ON COLUMN MEMBER.EMAIL IS '�̸���';
   COMMENT ON COLUMN MEMBER.PHONE IS '��ȭ��ȣ';
   COMMENT ON COLUMN MEMBER.ADDRESS IS '�ּ�';
   COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '���Գ�¥';
   COMMENT ON COLUMN MEMBER.BLACKLIST_FLAG IS '������Ʈ �÷���';
   COMMENT ON COLUMN MEMBER.ADMIN_FLAG IS '������ �÷���';
   COMMENT ON COLUMN MEMBER.PROFILE_IMG_ORINAME IS '�������̹��� ���� �̸�';
   COMMENT ON COLUMN MEMBER.PROFILE_IMG_RENAME IS '�������̹��� ����� �̸�';
   COMMENT ON COLUMN MEMBER.LAST_LOGIN_DATE IS '������ �α��� ��¥';
   COMMENT ON COLUMN MEMBER.ADDRESS_NUM IS '���� ��ȣ';
   
--SELECT * FROM MEMBER;
----------------------------------------------------------------------------------------------------------------

DROP TABLE MEMBER_ACCOUNT CASCADE CONSTRAINTS;

 CREATE TABLE MEMBER_ACCOUNT (	
    MEMBER_ID VARCHAR2(30), 
	ACCOUNT_NUMBER VARCHAR2(40), 
    BANK_ID VARCHAR2(20), 
    
    CONSTRAINT FK_MEMBERACCOUNT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBERACCOUNT_BANK_ID FOREIGN KEY (BANK_ID) REFERENCES BANK (BANK_ID) ON DELETE SET NULL
);

   COMMENT ON COLUMN MEMBER_ACCOUNT.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN MEMBER_ACCOUNT.ACCOUNT_NUMBER IS '���¹�ȣ';
   COMMENT ON COLUMN MEMBER_ACCOUNT.BANK_ID IS '���� ���̵�';
  
  
   
--SELECT * FROM MEMBER_ACCOUNT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE T_MEM_RPT_COUNT CASCADE CONSTRAINTS;

 CREATE TABLE T_MEM_RPT_COUNT (	
    MEMBER_ID VARCHAR2(30), 
	TOTAL_REPORT_COUNT NUMBER DEFAULT 0, 
    
    CONSTRAINT FK_T_MEM_RPT_COUNT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN T_MEM_RPT_COUNT.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN T_MEM_RPT_COUNT.TOTAL_REPORT_COUNT IS '�� �Ű� Ƚ��';
  
   
--SELECT * FROM T_MEM_RPT_COUNT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE CATEGORY (	
    CATEGORY_ID VARCHAR2(10) CONSTRAINT PK_CATEGORY PRIMARY KEY, 
	CATEGORY_NAME VARCHAR2(50)
);

   COMMENT ON COLUMN CATEGORY.CATEGORY_ID IS '��ī�װ� ���̵�';
   COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '�� ī�װ� �̸�';
  
   
--SELECT * FROM CATEGORY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE CATEGORY_SUB CASCADE CONSTRAINTS;

 CREATE TABLE CATEGORY_SUB (	
    CATEGORY_SUB_ID VARCHAR2(10) CONSTRAINT PK_CATEGORY_SUB PRIMARY KEY, 
	CATEGORY_SUB_NAME VARCHAR2(50),
    CATEGORY_ID VARCHAR2(10), 
	
    CONSTRAINT FK_CATEGORY_SUB_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN CATEGORY_SUB.CATEGORY_SUB_ID IS '��ī�װ� ���̵�';
   COMMENT ON COLUMN CATEGORY_SUB.CATEGORY_SUB_NAME IS '��ī�װ� �̸�';
   COMMENT ON COLUMN CATEGORY_SUB.CATEGORY_ID IS '��ī�װ� ���̵�';
  
--SELECT * FROM CATEGORY_SUB;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PROJECT_CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE PROJECT_CATEGORY (	
    PROJECT_CATEGORY_ID VARCHAR2(10) CONSTRAINT PK_PROJECT_CATEGORY PRIMARY KEY, 
	PROJECT_CATEGORY_NAME VARCHAR2(30)
);

   COMMENT ON COLUMN PROJECT_CATEGORY.PROJECT_CATEGORY_ID IS '������Ʈ ī�װ� ���̵�';
   COMMENT ON COLUMN PROJECT_CATEGORY.PROJECT_CATEGORY_NAME IS '������Ʈ ī�װ� �̸�';
  
--SELECT * FROM PROJECT_CATEGORY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PROJECT CASCADE CONSTRAINTS;

 CREATE TABLE PROJECT (	
    PROJECT_ID VARCHAR2(40) CONSTRAINT PK_PROJECT PRIMARY KEY, 
	PROJECT_CATEGORY_ID VARCHAR2(10), 
    CATEGORY_SUB_ID VARCHAR2(10), 
	PROJECT_NAME VARCHAR2(1000),
	MEMBER_ID VARCHAR2(30), 
	IMAGE_ORINAME VARCHAR2(1000), 
    IMAGE_RENAME VARCHAR2(1000), 
	REP_CONTENT VARCHAR2(4000), 
	TARGET_AMOUNT NUMBER, 
	CREATION_DATE DATE,
    START_DATE DATE,
    END_DATE DATE,
    PAYMENT_DATE DATE,
    REFUND_ROLE VARCHAR2(4000),
    PROJECT_REQUEST_FLAG VARCHAR2(1) CHECK(PROJECT_REQUEST_FLAG IN ('Y', 'N')),
    PROJECT_ONOFF_FLAG VARCHAR2(1) CHECK(PROJECT_ONOFF_FLAG IN ('Y', 'N')),
    REPORT_COUNT NUMBER DEFAULT 0,
    CERTIF_FLAG VARCHAR2(1) CHECK(CERTIF_FLAG IN ('Y', 'N')),
    
    CONSTRAINT FK_PROJECT_PROJECT_CATEGORY_ID FOREIGN KEY (PROJECT_CATEGORY_ID) REFERENCES PROJECT_CATEGORY (PROJECT_CATEGORY_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PROJECT_CATEGORY_SUB_ID FOREIGN KEY (CATEGORY_SUB_ID) REFERENCES CATEGORY_SUB (CATEGORY_SUB_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PROJECT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN PROJECT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN PROJECT.PROJECT_CATEGORY_ID IS '������Ʈ ī�װ� ���̵�';
   COMMENT ON COLUMN PROJECT.CATEGORY_SUB_ID IS '��ī�װ� ���̵�';
   COMMENT ON COLUMN PROJECT.PROJECT_NAME IS '������Ʈ �̸�';
   COMMENT ON COLUMN PROJECT.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN PROJECT.IMAGE_ORINAME IS '��ǥ�̹��� ���� ���ϸ�';
   COMMENT ON COLUMN PROJECT.IMAGE_RENAME IS '��ǥ�̹��� ����� ���ϸ�';
   COMMENT ON COLUMN PROJECT.REP_CONTENT IS '������Ʈ ����';
   COMMENT ON COLUMN PROJECT.TARGET_AMOUNT IS '��ǥ�ݾ�';
   COMMENT ON COLUMN PROJECT.CREATION_DATE IS '�����';
   COMMENT ON COLUMN PROJECT.START_DATE IS '������';
   COMMENT ON COLUMN PROJECT.END_DATE IS '������';
   COMMENT ON COLUMN PROJECT.PAYMENT_DATE IS '������';
   COMMENT ON COLUMN PROJECT.REFUND_ROLE IS 'ȯ����å';
   COMMENT ON COLUMN PROJECT.PROJECT_REQUEST_FLAG IS '������Ʈ ���� ��û �÷���';
   COMMENT ON COLUMN PROJECT.PROJECT_ONOFF_FLAG IS '������Ʈ ��Ȱ��ȭ �÷���';
   COMMENT ON COLUMN PROJECT.REPORT_COUNT IS '�Ű� Ƚ��';
   COMMENT ON COLUMN PROJECT.CERTIF_FLAG IS '���� ����';
  
   
--SELECT * FROM PROJECT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PROJECT_CONTENT CASCADE CONSTRAINTS;

 CREATE TABLE PROJECT_CONTENT (	
    PROJECT_ID VARCHAR2(40), 
	VIDEO_URL VARCHAR2(600), 
    CONTENT VARCHAR2(4000), 
    
    CONSTRAINT FK_PROJECT_CONTENT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN PROJECT_CONTENT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN PROJECT_CONTENT.VIDEO_URL IS '�Ұ� ���� URL';
   COMMENT ON COLUMN PROJECT_CONTENT.CONTENT IS '�� ����';
  
  
   
--SELECT * FROM PROJECT_CONTENT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE GIFT CASCADE CONSTRAINTS;

 CREATE TABLE GIFT (	
    GIFT_ID VARCHAR2(50) CONSTRAINT PK_GIFT PRIMARY KEY, 
	SUPPORT_PRICE NUMBER DEFAULT 0, 
    CAPACITY NUMBER DEFAULT 0, 
	PROJECT_ID VARCHAR2(40),
    
    CONSTRAINT FK_GIFT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN GIFT.GIFT_ID IS '���� ���̵�';
   COMMENT ON COLUMN GIFT.SUPPORT_PRICE IS '�Ŀ� �ݾ�';
   COMMENT ON COLUMN GIFT.CAPACITY IS '�ִ� ����';
   COMMENT ON COLUMN GIFT.PROJECT_ID IS '������Ʈ ���̵�';
   
--SELECT * FROM GIFT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE ITEM CASCADE CONSTRAINTS;

 CREATE TABLE ITEM (	
    ITEM_ID VARCHAR2(50) CONSTRAINT PK_ITEM PRIMARY KEY, 
	ITEM_NAME VARCHAR2(1000), 
    PROJECT_ID VARCHAR2(40), 
    
    CONSTRAINT FK_ITEM_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN ITEM.ITEM_ID IS '������ ���̵�';
   COMMENT ON COLUMN ITEM.ITEM_NAME IS '������ �̸�';
   COMMENT ON COLUMN ITEM.PROJECT_ID IS '������Ʈ ���̵�';
  
   
--SELECT * FROM ITEM;
----------------------------------------------------------------------------------------------------------------

DROP TABLE GIFT_IN_ITEMS CASCADE CONSTRAINTS;

 CREATE TABLE GIFT_IN_ITEMS (	
    GIFT_ID VARCHAR2(50), 
	ITEM_ID VARCHAR2(50), 
    COUNT NUMBER DEFAULT 1,

    CONSTRAINT FK_GIFT_IN_ITEMS_GIFT_ID FOREIGN KEY (GIFT_ID) REFERENCES GIFT (GIFT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_GIFT_IN_ITEMS_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN GIFT_IN_ITEMS.GIFT_ID IS '���� ���̵�';
   COMMENT ON COLUMN GIFT_IN_ITEMS.ITEM_ID IS '������ ���̵�';
   COMMENT ON COLUMN GIFT_IN_ITEMS.COUNT IS '������ ����';
  
   
--SELECT * FROM GIFT_IN_ITEMS;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PRODUCT CASCADE CONSTRAINTS;

 CREATE TABLE PRODUCT (	
    PRODUCT_ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY, 
	PROJECT_ID VARCHAR2(40), 
    PRODUCT_NAME VARCHAR2(500), 
	CAPACITY NUMBER DEFAULT 0,
    
    CONSTRAINT FK_PRODUCT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '�������� ��ǰ ���̵�';
   COMMENT ON COLUMN PRODUCT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '��ǰ��';
   COMMENT ON COLUMN PRODUCT.CAPACITY IS '�ִ� ����';
  
--SELECT * FROM PRODUCT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PROJECT_ACCOUNT CASCADE CONSTRAINTS;

 CREATE TABLE PROJECT_ACCOUNT (	
    PROJECT_ID VARCHAR2(40), 
	BANK_ID VARCHAR2(20), 
    ACCOUNT_NAME VARCHAR2(100), 
	ACCOUNT_NUMBER VARCHAR2(100),
    
    CONSTRAINT FK_PROJECT_ACCOUNT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROJECT_ACCOUNT_BANK_ID FOREIGN KEY (BANK_ID) REFERENCES BANK (BANK_ID) ON DELETE SET NULL
);

   COMMENT ON COLUMN PROJECT_ACCOUNT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN PROJECT_ACCOUNT.BANK_ID IS '�ŷ� ���� ���̵�';
   COMMENT ON COLUMN PROJECT_ACCOUNT.ACCOUNT_NAME IS '�����ָ�';
   COMMENT ON COLUMN PROJECT_ACCOUNT.ACCOUNT_NUMBER IS '���� ��ȣ';
  
   
--SELECT * FROM PROJECT_ACCOUNT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PROJECT_REPLY CASCADE CONSTRAINTS;

 CREATE TABLE PROJECT_REPLY (	
    PROJECT_REPLY_ID NUMBER CONSTRAINT PK_PROJECT_REPLY PRIMARY KEY, 
	MEMBER_ID VARCHAR2(30), 
    PROJECT_ID VARCHAR2(40), 
	REPLY_CONTENT VARCHAR2(1000),
	CREATION_DATE DATE, 
	REPLY_LEVEL NUMBER, 
    REPORT_COUNT NUMBER DEFAULT 0, 
	PROJ_REPLY_ID_REF NUMBER, 
    
    CONSTRAINT FK_PROJECT_REPLY_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PROJECT_REPLY_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_P_REPLY_PROJ_REPLY_ID_REF FOREIGN KEY (PROJ_REPLY_ID_REF) REFERENCES PROJECT_REPLY (PROJECT_REPLY_ID) ON DELETE CASCADE
);

  
   COMMENT ON COLUMN PROJECT_REPLY.PROJECT_REPLY_ID IS '������Ʈ ��� ���̵�';
   COMMENT ON COLUMN PROJECT_REPLY.MEMBER_ID IS '��� �ۼ��� ���̵�';
   COMMENT ON COLUMN PROJECT_REPLY.PROJECT_ID IS '���� ���̵�(������Ʈ ���̵�)';
   COMMENT ON COLUMN PROJECT_REPLY.REPLY_CONTENT IS '����';
   COMMENT ON COLUMN PROJECT_REPLY.CREATION_DATE IS '�ۼ���';
   COMMENT ON COLUMN PROJECT_REPLY.REPLY_LEVEL IS '��� ����';
   COMMENT ON COLUMN PROJECT_REPLY.REPORT_COUNT IS '�Ű� Ƚ��';
   COMMENT ON COLUMN PROJECT_REPLY.PROJ_REPLY_ID_REF IS '������Ʈ ��� ���̵�(���ۿ�)';
   
--SELECT * FROM PROJECT_REPLY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE LIKES CASCADE CONSTRAINTS;

 CREATE TABLE LIKES (	
    PROJECT_ID VARCHAR2(40), 
	MEMBER_ID VARCHAR2(30), 
    
    CONSTRAINT FK_LIKES_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKES_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN LIKES.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN LIKES.MEMBER_ID IS 'ȸ�� ���̵�';
     
--SELECT * FROM LIKES;
----------------------------------------------------------------------------------------------------------------

DROP TABLE MEMBER_TRUST CASCADE CONSTRAINTS;

 CREATE TABLE MEMBER_TRUST (	
    PROJECT_ID VARCHAR2(40), 
	MEMBER_ID VARCHAR2(30), 
    CORN_GRADE NUMBER DEFAULT 5, 
    CREATION_DATE DATE, 
    
    CONSTRAINT FK_MEMBER_TRUST_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_TRUST_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN MEMBER_TRUST.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN MEMBER_TRUST.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN MEMBER_TRUST.CORN_GRADE IS '�� ����';
   COMMENT ON COLUMN MEMBER_TRUST.CREATION_DATE IS '���� ��¥';
     
--SELECT * FROM MEMBER_TRUST;
----------------------------------------------------------------------------------------------------------------

DROP TABLE PAYMENT CASCADE CONSTRAINTS;

 CREATE TABLE PAYMENT (	
    PAYMENT_ID VARCHAR2(50), 
    MEMBER_ID VARCHAR2(30), 
    PROJECT_ID VARCHAR2(40),
	GIFT_ID VARCHAR2(50), 
    PRODUCT_ID NUMBER, 
    TOTAL_AMOUNT NUMBER DEFAULT 0, 
    TOTAL_COUNT NUMBER DEFAULT 1, 
    PAYMENT_DATE DATE, 
    REFUND_DATE DATE, 
    REFUND_FLAG VARCHAR2(1) CHECK(REFUND_FLAG IN ('Y', 'N')), 
    
    CONSTRAINT FK_PAYMENT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PAYMENT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PAYMENT_GIFT_ID FOREIGN KEY (GIFT_ID) REFERENCES GIFT (GIFT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PAYMENT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE SET NULL
);

   COMMENT ON COLUMN PAYMENT.PAYMENT_ID IS '���� ���̵�';
   COMMENT ON COLUMN PAYMENT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN PAYMENT.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN PAYMENT.GIFT_ID IS '���� ���̵�';
   COMMENT ON COLUMN PAYMENT.PRODUCT_ID IS '�������� ��ǰ ���̵�';
   COMMENT ON COLUMN PAYMENT.TOTAL_AMOUNT IS '�� �ݾ�';
   COMMENT ON COLUMN PAYMENT.TOTAL_COUNT IS '���� ����';
   COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '������';
   COMMENT ON COLUMN PAYMENT.REFUND_DATE IS 'ȯ�ҳ�¥';
   COMMENT ON COLUMN PAYMENT.REFUND_FLAG IS 'ȯ�� ���� �÷���';
     
--SELECT * FROM PAYMENT;
----------------------------------------------------------------------------------------------------------------



DROP TABLE BOARD_CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE BOARD_CATEGORY (	
    BOARD_CATEGORY_ID VARCHAR2(10) CONSTRAINT PK_BOARD_CATEGORY PRIMARY KEY, 
	BOARD_CATEGORY_NAME VARCHAR2(30)
);

   COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CATEGORY_ID IS '�Խñ� ī�װ� ���̵�';
   COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CATEGORY_NAME IS '�Խñ� ī�װ� �̸�';
     
--SELECT * FROM BOARD_CATEGORY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE BOARD CASCADE CONSTRAINTS;

 CREATE TABLE BOARD (	
    BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY, 
	BOARD_CATEGORY_ID VARCHAR2(10), 
    MEMBER_ID VARCHAR2(30), 
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(4000), 
	CREATION_DATE DATE, 
    READCOUNT NUMBER  DEFAULT 0, 
	RECOMMEND_COUNT NUMBER  DEFAULT 0, 
    REPORT_COUNT NUMBER  DEFAULT 0, 
    ORI_FILENAME VARCHAR2(100), 
    RE_FILENAME VARCHAR2(100), 
    
    CONSTRAINT FK_BOARD_BOARD_CATEGORY_ID FOREIGN KEY (BOARD_CATEGORY_ID) REFERENCES BOARD_CATEGORY (BOARD_CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL
);

   COMMENT ON COLUMN BOARD.BOARD_ID IS '�Խñ� ���̵�';
   COMMENT ON COLUMN BOARD.BOARD_CATEGORY_ID IS '�Խñ� ī�װ� ���̵�';
   COMMENT ON COLUMN BOARD.MEMBER_ID IS '�ۼ���';
   COMMENT ON COLUMN BOARD.TITLE IS '����';
   COMMENT ON COLUMN BOARD.CONTENT IS '����';
   COMMENT ON COLUMN BOARD.CREATION_DATE IS '�ۼ���';
   COMMENT ON COLUMN BOARD.READCOUNT IS '��ȸ��';
   COMMENT ON COLUMN BOARD.RECOMMEND_COUNT IS '��õ��';
   COMMENT ON COLUMN BOARD.REPORT_COUNT IS '�Ű� Ƚ��';
   COMMENT ON COLUMN BOARD.ORI_FILENAME IS '���� ���� �̸�';
   COMMENT ON COLUMN BOARD.RE_FILENAME IS '���� ����� �̸�';
    
--SELECT * FROM BOARD;
----------------------------------------------------------------------------------------------------------------

DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;

 CREATE TABLE BOARD_REPLY (	
    BOARD_REPLY_ID NUMBER CONSTRAINT PK_BOARD_REPLY PRIMARY KEY, 
	MEMBER_ID VARCHAR2(30), 
    BOARD_ID NUMBER, 
	BOARD_CONTENT VARCHAR2(1000),
	CREATION_DATE DATE, 
	BOARD_LEVEL NUMBER, 
    REPORT_COUNT NUMBER  DEFAULT 0, 
	BOARD_REPLY_ID_REF NUMBER, 
    
    CONSTRAINT FK_BOARD_REPLY_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_BOARD_REPLY_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_REPLY_B_REPLY_ID_REF FOREIGN KEY (BOARD_REPLY_ID_REF) REFERENCES BOARD_REPLY (BOARD_REPLY_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN BOARD_REPLY.BOARD_REPLY_ID IS '�Խñ� ��� ���̵�';
   COMMENT ON COLUMN BOARD_REPLY.MEMBER_ID IS '��� �ۼ��� ���̵�';  
   COMMENT ON COLUMN BOARD_REPLY.BOARD_ID IS '���� ���̵�(�Խñ� ���̵�)';
   COMMENT ON COLUMN BOARD_REPLY.BOARD_CONTENT IS '����';
   COMMENT ON COLUMN BOARD_REPLY.CREATION_DATE IS '�ۼ���';
   COMMENT ON COLUMN BOARD_REPLY.BOARD_LEVEL IS '��� ����';
   COMMENT ON COLUMN BOARD_REPLY.REPORT_COUNT IS '�Ű� Ƚ��';
   COMMENT ON COLUMN BOARD_REPLY.BOARD_REPLY_ID_REF IS '�Խñ� ��� ���̵�(���ۿ�)';
    
--SELECT * FROM BOARD_REPLY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE QUESTION_CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE QUESTION_CATEGORY (	
    QUESTION_CATEGORY_ID VARCHAR2(10) CONSTRAINT PK_QUESTION_CATEGORY PRIMARY KEY, 
	QUESTION_CATEGORY_NAME VARCHAR2(50)
);

   COMMENT ON COLUMN QUESTION_CATEGORY.QUESTION_CATEGORY_ID IS '������ ī�װ�';
   COMMENT ON COLUMN QUESTION_CATEGORY.QUESTION_CATEGORY_NAME IS '������ ī�װ� �̸�';
     
--SELECT * FROM QUESTION_CATEGORY;
----------------------------------------------------------------------------------------------------------------


DROP TABLE QUESTION CASCADE CONSTRAINTS;

 CREATE TABLE QUESTION (	
    QUESTION_ID NUMBER CONSTRAINT PK_QUESTION PRIMARY KEY, 
	QUESTION_CATEGORY_ID VARCHAR2(10), 
    RECEIVE_MEMBER_ID VARCHAR2(30), 
	SEND_MEMBER_ID VARCHAR2(30),
	TITLE VARCHAR2(100), 
	CONTENT VARCHAR2(500), 
    RE_CONTENT VARCHAR2(500), 
    SEND_CREATION_DATE DATE,
    RECEIVE_CREATION_DATE DATE,
    
    CONSTRAINT FK_QUESTION_QCATEGORY_ID FOREIGN KEY (QUESTION_CATEGORY_ID) REFERENCES QUESTION_CATEGORY (QUESTION_CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_QUESTION_RECEIVE_MEMBER_ID FOREIGN KEY (RECEIVE_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_QUESTION_SEND_MEMBER_ID FOREIGN KEY (SEND_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL
);

  
   COMMENT ON COLUMN QUESTION.QUESTION_ID IS '������ ���̵�';
   COMMENT ON COLUMN QUESTION.QUESTION_CATEGORY_ID IS '������ ī�װ�';
   COMMENT ON COLUMN QUESTION.RECEIVE_MEMBER_ID IS '�޴� ȸ�� ���̵�';
   COMMENT ON COLUMN QUESTION.SEND_MEMBER_ID IS '������ ȸ�� ���̵�';
   COMMENT ON COLUMN QUESTION.TITLE IS '������ ����';
   COMMENT ON COLUMN QUESTION.CONTENT IS '������ ����';
   COMMENT ON COLUMN QUESTION.RE_CONTENT IS '������ �亯 ����';
   COMMENT ON COLUMN QUESTION.SEND_CREATION_DATE IS '���� �ۼ� ��¥';
   COMMENT ON COLUMN QUESTION.RECEIVE_CREATION_DATE IS '���� �亯 ��¥';
    
--SELECT * FROM QUESTION;
----------------------------------------------------------------------------------------------------------------

DROP TABLE REPORT_CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE REPORT_CATEGORY (	
    REPORT_CATEGORY_ID VARCHAR2(10) CONSTRAINT PK_REPORT_CATEGORY PRIMARY KEY, 
	REPORT_CATEGORY_NAME VARCHAR2(50)
);

   COMMENT ON COLUMN REPORT_CATEGORY.REPORT_CATEGORY_ID IS '�Ű� ī�װ� ���̵�';
   COMMENT ON COLUMN REPORT_CATEGORY.REPORT_CATEGORY_NAME IS '�Ű� ī�װ� �̸�';
     
--SELECT * FROM REPORT_CATEGORY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE REPORT CASCADE CONSTRAINTS;

 CREATE TABLE REPORT (   
    REPORT_ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY, 
   REPORT_CATEGORY_ID VARCHAR2(10), 
    PROJECT_ID VARCHAR2(40), 
   PROJECT_REPLY_ID NUMBER,
   BOARD_ID NUMBER, 
   BOARD_REPLY_ID NUMBER, 
    REPORT_REASON VARCHAR2(200), 
   MEMBER_ID VARCHAR2(30), 
    REPORT_DATE DATE, 
    REPORT_READ_FLAG VARCHAR2(1) CHECK(REPORT_READ_FLAG IN ('Y', 'N')),
    
    CONSTRAINT FK_REPORT_REPORT_CATEGORY_ID FOREIGN KEY (REPORT_CATEGORY_ID) REFERENCES REPORT_CATEGORY (REPORT_CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_PROJECT_REPLY_ID FOREIGN KEY (PROJECT_REPLY_ID) REFERENCES PROJECT_REPLY (PROJECT_REPLY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_BOARD_REPLY_ID FOREIGN KEY (BOARD_REPLY_ID) REFERENCES BOARD_REPLY (BOARD_REPLY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

   COMMENT ON COLUMN REPORT.REPORT_ID IS '�Ű� ���̵�';
   COMMENT ON COLUMN REPORT.REPORT_CATEGORY_ID IS '�Ű� ī�װ� ���̵�';
   COMMENT ON COLUMN REPORT.PROJECT_ID IS '������Ʈ ���̵�';
   COMMENT ON COLUMN REPORT.PROJECT_REPLY_ID IS '������Ʈ ��� ���̵�';
   COMMENT ON COLUMN REPORT.BOARD_ID IS '�Խñ� ���̵�';
   COMMENT ON COLUMN REPORT.BOARD_REPLY_ID IS '�Խñ� ��� ���̵�';
   COMMENT ON COLUMN REPORT.REPORT_REASON IS '�Ű� ����';
   COMMENT ON COLUMN REPORT.MEMBER_ID IS '�Ű��� ȸ��';
   COMMENT ON COLUMN REPORT.REPORT_DATE IS '�Ű� ��¥';
   COMMENT ON COLUMN REPORT.REPORT_READ_FLAG IS '�Ű� ���� ����';
    
--SELECT * FROM REPORT;
----------------------------------------------------------------------------------------------------------------

DROP TABLE NOTICE CASCADE CONSTRAINTS;

 CREATE TABLE NOTICE (	
    NOTICE_ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY, 
	TITLE VARCHAR2(100),
    CREATION_DATE DATE,
    CONTENT VARCHAR2(1000)
);

   COMMENT ON COLUMN NOTICE.NOTICE_ID IS '�������� ���̵�';
   COMMENT ON COLUMN NOTICE.TITLE IS '����';
   COMMENT ON COLUMN NOTICE.CREATION_DATE IS '�ۼ���';
   COMMENT ON COLUMN NOTICE.CONTENT IS '����';
        
--SELECT * FROM NOTICE;
----------------------------------------------------------------------------------------------------------------


DROP TABLE TABOO CASCADE CONSTRAINTS;

 CREATE TABLE TABOO (	
    CONTENT VARCHAR2(50)
);

   COMMENT ON COLUMN TABOO.CONTENT IS '�����ܾ�';
        
--SELECT * FROM TABOO;
----------------------------------------------------------------------------------------------------------------

DROP TABLE ALARM_CATEGORY CASCADE CONSTRAINTS;

 CREATE TABLE ALARM_CATEGORY (	
    ALA_CATE_ID VARCHAR2(30) CONSTRAINT PK_ALARM_CATEGORY PRIMARY KEY, 
	ALA_CATE_NAME VARCHAR2(50)
);

   COMMENT ON COLUMN ALARM_CATEGORY.ALA_CATE_ID IS '�˶� ī�װ� ���̵�';
   COMMENT ON COLUMN ALARM_CATEGORY.ALA_CATE_NAME IS '�˶� ī�װ� �̸�';  
   
--SELECT * FROM ALARM_CATEGORY;
----------------------------------------------------------------------------------------------------------------

DROP TABLE ALARM CASCADE CONSTRAINTS;

 CREATE TABLE ALARM (	
    ALARM_ID NUMBER CONSTRAINT PK_ALARM PRIMARY KEY, 
	ALA_CATE_ID VARCHAR2(30), 
    MEMBER_ID VARCHAR2(30), 
	CONTENT VARCHAR2(300),
	READ_FLAG VARCHAR2(1) CHECK(READ_FLAG IN ('Y', 'N')), 
    
    CONSTRAINT FK_ALARM_ALA_CATE_ID FOREIGN KEY (ALA_CATE_ID) REFERENCES ALARM_CATEGORY (ALA_CATE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALARM_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL
);

   COMMENT ON COLUMN ALARM.ALARM_ID IS '�˶� ���̵�';
   COMMENT ON COLUMN ALARM.ALA_CATE_ID IS '�˶� ī�װ� ���̵�';  
   COMMENT ON COLUMN ALARM.MEMBER_ID IS 'ȸ�� ���̵�';
   COMMENT ON COLUMN ALARM.CONTENT IS '����';
   COMMENT ON COLUMN ALARM.READ_FLAG IS '���� ����';
    
--SELECT * FROM ALARM;
----------------------------------------------------------------------------------------------------------------




