DROP TABLE MEMBER CASCADE CONSTRAINTS;

 CREATE TABLE MEMBER (	
    MEMBER_ID VARCHAR2(30) CONSTRAINT PK_MEMBER PRIMARY KEY, 
	MEMBER_PWD VARCHAR2(30) NOT NULL, 
    MEMBER_NAME VARCHAR2(50) NOT NULL, 
	AGE NUMBER NOT NULL, 
	GENDER VARCHAR2(1) CHECK (GENDER IN ('M','F')), 
	EMAIL VARCHAR2(40), 
    PHONE VARCHAR2(30), 
	ADDRESS VARCHAR2(500), 
	ENROLL_DATE DATE, 
	BLACKLIST_FLAG VARCHAR2(1) CHECK(BLACKLIST_FLAG IN ('Y', 'N')),
    ADMIN_FLAG VARCHAR2(1) CHECK(ADMIN_FLAG IN ('Y', 'N')),
    PROFILE_IMG_ORINAME VARCHAR2(100),
    PROFILE_IMG_RENAME VARCHAR2(100)
);

   COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
   COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '비밀번호';
   COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';
   COMMENT ON COLUMN MEMBER.AGE IS '나이';
   COMMENT ON COLUMN MEMBER.GENDER IS '성별';
   COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
   COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
   COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
   COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입날짜';
   COMMENT ON COLUMN MEMBER.BLACKLIST_FLAG IS '블랙리스트 플래그';
   COMMENT ON COLUMN MEMBER.ADMIN_FLAG IS '관리자 플래그';
   COMMENT ON COLUMN MEMBER.PROFILE_IMG_ORINAME IS '프로필이미지 원래 이름';
   COMMENT ON COLUMN MEMBER.PROFILE_IMG_RENAME IS '프로필이미지 변경된 이름';
  
   
--SELECT * FROM MEMBER;
----------------------------------------------------------------------------------------------------------------