CREATE OR REPLACE VIEW V_GIFTINITEMSUPDATE(
GIFT_ID, ITEM_ID, COUNT, PROJECT_ID
)
AS 
SELECT GII.GIFT_ID,
       GII.ITEM_ID,
       GII.COUNT,
       G.PROJECT_ID
FROM GIFT_IN_ITEMS GII 
LEFT JOIN GIFT G ON(GII.GIFT_ID = G.GIFT_ID)
;

