  CREATE OR REPLACE FORCE VIEW "CORNSALAD"."P_GIFT" ("PROJECT_ID", "GIFT_ID", "SUPPORT_PRICE","CAPACITY","REMAIN") AS 
  SELECT PC.PROJECT_ID,PC.GIFT_ID,G.SUPPORT_PRICE, G.CAPACITY, (g.capacity-sum(COUNT)) AS REMAIN
FROM PAYMENT_COUNT PC
LEFT JOIN GIFT G ON (PC.GIFT_ID = G.GIFT_ID)
GROUP BY PC.PROJECT_ID, PC.GIFT_ID, G.SUPPORT_PRICE, G.CAPACITY
ORDER BY SUPPORT_PRICE;
            
  CREATE OR REPLACE FORCE VIEW "CORNSALAD"."P_ITEMS" ("GIFT_ID", "ITEM_NAME", "COUNT") AS 
  SELECT GIFT_ID, ITEM_NAME, COUNT
FROM GIFT_IN_ITEMS GI 
JOIN ITEM I ON (GI.ITEM_ID = I.ITEM_ID);

  CREATE OR REPLACE FORCE VIEW "CORNSALAD"."P_SELLERINFO" ("PROJECT_ID", "PROJECT_NAME", "MEMBER_NAME","PROFILE_IMG_RENAME", "END_DATE") AS 
  SELECT PROJECT_ID, PROJECT_NAME, MEMBER_NAME, PROFILE_IMG_RENAME , END_DATE
FROM PROJECT P
JOIN MEMBER M ON (P.MEMBER_ID = M.MEMBER_ID);