CREATE OR REPLACE VIEW V_PROJECTSTATUSUPDATE(
PROJECT_ID, PROJECT_CATEGORY_ID, CATEGORY_SUB_ID, PROJECT_NAME, 
MEMBER_ID, IMAGE_ORINAME, IMAGE_RENAME, REP_CONTENT, TARGET_AMOUNT,
CREATION_DATE, START_DATE, END_DATE, PAYMENT_DATE, 
REFUND_ROLE, PROJECT_REQUEST_FLAG, PROJECT_ONOFF_FLAG, REPORT_COUNT, 
CERTIF_FLAG, CATEGORY_ID
)
AS 
SELECT P.PROJECT_ID,
       P.PROJECT_CATEGORY_ID,
       P.CATEGORY_SUB_ID,
       P.PROJECT_NAME,
       P.MEMBER_ID,
       P.IMAGE_ORINAME,
       P.IMAGE_RENAME,
       P.REP_CONTENT,
       P.TARGET_AMOUNT,
       P.CREATION_DATE,
       P.START_DATE,
       P.END_DATE,
       P.PAYMENT_DATE,
       P.REFUND_ROLE,
       P.PROJECT_REQUEST_FLAG,
       P.PROJECT_ONOFF_FLAG,
       P.REPORT_COUNT,
       P.CERTIF_FLAG,
       CS.CATEGORY_ID
FROM PROJECT P 
LEFT JOIN CATEGORY_SUB CS ON(P.CATEGORY_SUB_ID = CS.CATEGORY_SUB_ID)
LEFT JOIN CATEGORY C ON(CS.CATEGORY_ID = C.CATEGORY_ID)
;

