--공동구매 상세 페이지 프로젝트와 구매 퍼센트 관련 VIEW
CREATE OR REPLACE VIEW V_PROJECTDETAIL_GROUPPAR(
PROJECT_ID, PROJECT_NAME, MEMBER_NAME, REP_CONTENT, START_DATE, END_DATE,
DDAY, PAYMENT_DATE, REFUND_ROLE, VIDEO_URL, CONTENT, PROJECT_CATEGORY_ID, 
PROJECT_CATEGORY_NAME, CATEGORY_SUB_ID, CATEGORY_SUB_NAME, CATEGORY_ID, 
CATEGORY_NAME, TARGET_AMOUNT, PERCENT
)
AS
    SELECT P.PROJECT_ID, 
           PROJECT_NAME,
           M.MEMBER_NAME, 
           REP_CONTENT, 
           START_DATE,
           END_DATE, 
           FLOOR(END_DATE-sysdate) AS DDAY,
           PAYMENT_DATE, 
           REFUND_ROLE, 
           VIDEO_URL, 
           CONTENT, 
           P.PROJECT_CATEGORY_ID, 
           PROJECT_CATEGORY_NAME,
           P.CATEGORY_SUB_ID, 
           CATEGORY_SUB_NAME, 
           CS.CATEGORY_ID, 
           CATEGORY_NAME,
           TARGET_AMOUNT,
            ROUND(NVL((SELECT SUM(NVL(PAYTOTAL.COUNT, 0)) AS SUM_PAY_COUNT
                        FROM PRODUCT PROD
                        LEFT JOIN (SELECT PAY.PROJECT_ID,
                                          PAYC.PRODUCT_ID,
                                          COUNT
                                    FROM PAYMENT PAY
                                    JOIN PAYMENT_COUNT PAYC ON(PAY.PAYMENT_ID = PAYC.PAYMENT_ID)
                                    WHERE PAYC.PRODUCT_ID IS NOT NULL) PAYTOTAL ON(PAYTOTAL.PRODUCT_ID = PROD.PRODUCT_ID)
                        WHERE PROD.PROJECT_ID = P.PROJECT_ID
                        GROUP BY (PROD.PROJECT_ID)),0)/NVL(TARGET_AMOUNT,0)*100) AS PERCENT
    FROM PROJECT P
    LEFT JOIN PROJECT_CONTENT CT ON(P.PROJECT_ID = CT.PROJECT_ID)
    JOIN PROJECT_CATEGORY PC ON(P.PROJECT_CATEGORY_ID = PC.PROJECT_CATEGORY_ID)
    JOIN CATEGORY_SUB CS ON(P.CATEGORY_SUB_ID = CS.CATEGORY_SUB_ID)
    JOIN CATEGORY C ON(CS.CATEGORY_ID = C.CATEGORY_ID)
    JOIN MEMBER M ON(P.MEMBER_ID=M.MEMBER_ID)
    WHERE PC.PROJECT_CATEGORY_ID = 'PC-PROD'
;


--상세 페이지에 보여줄 물품 목록과 갯수
CREATE OR REPLACE VIEW V_PRODUCT_DETAIL(
PROJECT_ID, PRODUCT_ID, PRODUCT_NAME, MINCOUNT, REST_COUNT, PAY_COUNT, PAYMENT_DATE
)
AS
    SELECT PROD.PROJECT_ID,
           PROD.PRODUCT_ID,
           PROD.PRODUCT_NAME,
           PROD.MINCOUNT,
           PROD.MINCOUNT - NVL(PAYC.COUNT, 0) AS REST_COUNT,
           NVL(PAYC.COUNT, 0) AS PAY_COUNT,
           PAYMENT_DATE + 7
    FROM PRODUCT PROD
    LEFT JOIN PAYMENT_COUNT PAYC ON(PROD.PRODUCT_ID = PAYC.PRODUCT_ID)
    JOIN PROJECT P ON(P.PROJECT_ID = PROD.PROJECT_ID)
    ORDER BY PROD.PRODUCT_ID
;